### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by shaib** [rtucker/gnucash-importers#1]
HI, I'd like to make and publish some scripts based on yours (particularly the PayPal importer), but with no license, I'm technically not allowed to do that. Would you be so kind as to add a license to this repo?

Thanks, and either way, thanks for sharing your work -- I can learn and imitate even if i can't simply use.

**Comment by rtucker** [comment]
Ah rats, thanks for catching this.  271d7981f46d2f027082e6f5416896760d222b40 adds MIT license for the project.

Also, standard self-deprecation disclaimer applies about learning and imitating from my code :) but please enjoy, and I hope it's useful!!
